name: pg-service

services:
  postgres:
    image: postgres:latest
    container_name: my_postgres
    env_file:
      - .env
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - postgres-network

networks:
  postgres-network:
    driver: bridge
